proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  default-proxy-max-lifetime: 120
  default-max-instances: 2
  max-total-instances: 10
  port: 8080
  authentication: none
  admin-groups: admins
  support:
    mail-to-address: andrea.bazzano@arpal.liguria.it
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
  - id: SIprecisa
    container-cmd: ["R", "-e", "SIprecisa::run_app()"]
    container-image: siprecisa:latest
    container-network: sp-example-net
    minimum-seats-available: 1
    allow-container-re-use: false
    hide-navbar-on-main-page-link: true
  - id: SIconfronta
    container-cmd: ["R", "-e", "SIconfronta::run_app()"]
    container-image: siconfronta:latest
    container-network: sp-example-net
    minimum-seats-available: 1
    allow-container-re-use: false
    hide-navbar-on-main-page-link: true
logging:
  file:
    shinyproxy.log
  level:
    root: WARN
